services:
  db:
    build: .
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_cron"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-extensions.sql:/docker-entrypoint-initdb.d/01-extensions.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
