name: Run Supabase Migrations

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.17.0'

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        env:
          NODE_ENV: production
          SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}
        run: |
          # Debug: Check if the variable is set (remove after debugging)
          echo "SUPABASE_DATABASE_URL is set: ${{ secrets.SUPABASE_DATABASE_URL != '' }}"
          
          # Run migrations
          #npx sequelize-cli db:migrate